/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package huffman;

import java.util.*;

/**
 * 
 * @author marouano
 */
public class Huffman {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        String str = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ornare nec ipsum a pretium. Morbi congue quam vitae mi rhoncus tempus. Fusce pellentesque sollicitudin mi eget porttitor. Donec pellentesque ante quis lacinia vulputate. Quisque augue lorem, lacinia nec ante at, eleifend vehicula augue. Nullam ornare ante erat, ut dignissim quam cursus at. Maecenas euismod lorem et mi pellentesque elementum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vitae velit lectus.\n" +
"\n" +
"Aliquam et sapien odio. Nunc tincidunt eget metus a gravida. Nulla molestie aliquet eros in faucibus. Suspendisse aliquet, ex sit amet malesuada sagittis, massa mi luctus nisl, et euismod eros libero vitae ante. Phasellus luctus posuere leo eu mollis. Sed iaculis luctus sem vel tempor. Sed dignissim non est consectetur mattis. Maecenas quis metus nec nisi suscipit luctus ac at ante. Nulla placerat nisi nec lectus elementum varius. Aenean sollicitudin nisl et elementum mollis. Praesent commodo tincidunt ipsum euismod viverra.\n" +
"\n" +
"Donec tempor lorem nisl, porttitor maximus risus aliquet ac. Aliquam fermentum lacinia nunc, vitae iaculis purus tincidunt viverra. Fusce dictum mauris sit amet vulputate dapibus. Sed sapien diam, efficitur vitae venenatis eget, egestas nec augue. Aenean maximus tincidunt felis. Nulla ac orci et mauris pretium posuere eget ut justo. Morbi ac sapien massa. Duis sed ipsum ultricies, consectetur nunc non, dignissim velit. Quisque laoreet congue risus, non dictum mauris varius tincidunt. Aenean quis velit velit. Nunc pretium vehicula viverra. Sed volutpat tristique nisi, eget viverra felis facilisis placerat. Ut id pretium tortor, in vulputate urna. Vivamus metus leo, vulputate placerat mi at, dapibus lacinia ipsum. Nulla in pulvinar arcu, id bibendum ipsum.\n" +
"\n" +
"Pellentesque ac dignissim odio. Nulla at turpis nibh. Praesent sagittis nisl in luctus vehicula. Sed tincidunt elit eget nisi pretium, eu mattis sem tincidunt. Praesent gravida malesuada leo eget porta. Praesent viverra laoreet mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fermentum, enim in tristique finibus, tortor eros pharetra elit, eu eleifend tortor enim ac tortor. Vestibulum mi ligula, imperdiet eu purus eget, dictum fermentum est.\n" +
"\n" +
"Aliquam tellus lorem, congue in est sit amet, vestibulum varius ante. Nulla tempus enim elit, ac venenatis eros eleifend quis. Aliquam ac est in sapien tempor congue. Duis lobortis hendrerit lectus quis placerat. In hac habitasse platea dictumst. Nullam feugiat elit ut ex facilisis aliquet. Nunc vulputate libero eget justo posuere, vel placerat tellus ultrices. Quisque tempus pretium enim ac pellentesque. Nam varius mi id euismod commodo. Quisque fringilla, est iaculis vulputate luctus, nisl lorem euismod nulla, quis vehicula massa nisi nec arcu. Proin id feugiat elit, in finibus nisl. Etiam ut urna tincidunt metus dignissim mattis. Sed porttitor libero metus, ac feugiat tellus mattis ac. Nulla facilisi. Vivamus a tellus consequat, egestas tortor vel, auctor nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n" +
"\n" +
"Vivamus ex ipsum, tristique a lobortis eu, dictum ut sem. Morbi tempus vitae tortor quis molestie. Maecenas nulla lacus, pulvinar vel tortor dignissim, consequat cursus enim. Pellentesque vel velit tincidunt, tristique mi ut, cursus mauris. Nam nec consectetur tortor. Etiam dignissim imperdiet porttitor. Aliquam at nunc vitae leo auctor vulputate nec quis augue. Sed luctus a nulla eu volutpat. Nulla mollis, justo a aliquet efficitur, ligula sem aliquam justo, sed pulvinar nunc felis ac felis. Aenean non viverra nunc. Phasellus non sapien vel risus mollis feugiat vitae eu mauris.\n" +
"\n" +
"Ut consectetur faucibus leo a semper. Donec et tempor odio. Nullam leo eros, dapibus eu massa et, viverra aliquet mauris. Vivamus tempor mauris id velit semper, vel tempor ipsum blandit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin lacinia purus non sem maximus scelerisque. Curabitur vel nibh vel felis pulvinar suscipit.\n" +
"\n" +
"Aliquam sit amet ex feugiat, elementum mauris eu, porttitor libero. Proin dapibus tempor massa, vel blandit odio porta ut. Mauris consectetur tortor ac metus tincidunt rutrum. Nullam viverra sem eu risus ullamcorper, vitae lobortis urna imperdiet. Nulla imperdiet quam libero, nec maximus enim maximus vitae. Nam pellentesque congue faucibus. Integer vitae feugiat lacus. Vestibulum in lectus eget dui venenatis aliquam at eu purus. In accumsan nulla id risus porta lobortis. Etiam posuere faucibus enim, at finibus purus euismod porta. Cras sit amet luctus nunc. Praesent blandit vulputate dui. Duis suscipit ante nibh. Suspendisse nec diam vel ante consequat egestas vel vel tortor. Donec cursus justo at placerat vestibulum. Suspendisse porttitor justo eu maximus tempor.\n" +
"\n" +
"Aliquam ante augue, ultrices ac rutrum ut, pulvinar ac metus. Maecenas at nisl venenatis, fringilla leo vitae, maximus magna. Praesent porttitor imperdiet congue. Donec ut varius velit, a cursus leo. Phasellus metus magna, efficitur eu sodales mattis, pulvinar non velit. Curabitur fringilla interdum felis, a placerat magna tristique vehicula. Nam et elementum tellus. Maecenas eget molestie turpis. Quisque fermentum felis porttitor varius lacinia. Integer mattis nunc eget bibendum consequat. Sed vel nisi aliquet, tempus tellus sed, laoreet orci.\n" +
"\n" +
"Nunc auctor accumsan eleifend. Etiam quis nisl eleifend, lacinia neque ac, volutpat lectus. Donec non scelerisque tellus. Duis in mollis ligula. Nulla risus sem, tempus id sem quis, congue accumsan nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec molestie finibus elit, sit amet efficitur elit condimentum eu.\n" +
"\n" +
"Pellentesque tincidunt nec mi eu interdum. Aliquam erat volutpat. Sed at odio egestas, mattis quam eu, sagittis turpis. Proin lorem eros, volutpat ac orci sed, aliquam aliquam diam. Nullam faucibus gravida libero. Etiam nec commodo dui. Mauris dictum turpis ac ipsum tincidunt pretium. Nam placerat tincidunt lacinia. Ut ut ultricies velit, eget cursus ex.\n" +
"\n" +
"Sed sapien augue, imperdiet in iaculis at, luctus id sem. Phasellus mauris mauris, lobortis eget nulla et, tempus varius tortor. Vivamus bibendum eros nec libero tincidunt consequat. Donec lacinia congue arcu, a faucibus felis varius quis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed mauris dui, bibendum sit amet auctor vel, luctus vel libero. Pellentesque sem lorem, congue eget nulla sit amet, consequat fermentum dui.\n" +
"\n" +
"Donec vitae diam feugiat, condimentum sem a, rutrum urna. Mauris mattis odio metus, et dictum orci lacinia ac. Aliquam dictum facilisis augue eu ultricies. Suspendisse ac nisl sed eros viverra tristique vitae non dolor. Donec et arcu tincidunt, fringilla sapien nec, iaculis felis. Donec molestie est scelerisque massa finibus aliquet. Suspendisse euismod est eu maximus porta. Fusce auctor placerat dolor, ac sollicitudin risus molestie vitae. Aenean maximus lacus quis aliquet posuere. Sed semper convallis tincidunt. Fusce sed augue non quam volutpat scelerisque. Sed blandit purus eget magna ornare, eu laoreet nisl placerat. Donec sed aliquet tortor, ac pretium nulla. Donec convallis suscipit augue non dignissim. Fusce mattis felis nunc, eu hendrerit mi posuere id.\n" +
"\n" +
"Donec quis dolor id risus bibendum malesuada. Nulla facilisi. Phasellus imperdiet vitae risus ac egestas. Integer felis erat, commodo id nisi sollicitudin, vulputate sollicitudin ex. Cras ipsum augue, luctus sed luctus sit amet, ultricies eget odio. Proin sagittis lobortis metus, eget laoreet lorem laoreet quis. Morbi sodales purus aliquet, consectetur odio vitae, fringilla tellus. Aenean lorem lacus, tempus eget est vel, vulputate consectetur felis. Praesent vitae justo ac turpis ullamcorper auctor. Sed in massa a diam accumsan porta. Ut tellus ex, tristique a suscipit in, dignissim vitae nunc. Aliquam in mi et nisi aliquet lobortis id eget erat.\n" +
"\n" +
"In quis mauris eros. Donec mauris nunc, iaculis vitae dignissim at, congue sed ipsum. Sed ultrices consectetur tortor porta ornare. Nulla condimentum ante in neque fermentum, in dignissim turpis ornare. Aenean auctor porta pretium. Pellentesque non tellus justo. Donec viverra scelerisque lorem, nec porta ex dapibus sed. Nam vehicula eget ex eu facilisis. Cras nec pharetra elit. Aenean purus odio, tempus ac lorem ut, viverra dignissim dui. In hac habitasse platea dictumst. Etiam nisi erat, scelerisque eget congue condimentum, rhoncus sit amet ligula. Phasellus nisi leo, elementum vitae luctus in, accumsan ut dui. Quisque volutpat aliquet molestie. Integer suscipit nisl ac nisl cursus, et ullamcorper velit pulvinar.\n" +
"\n" +
"Mauris in dolor elementum orci rutrum pellentesque. Praesent vitae dapibus velit. Etiam semper ut ex a rutrum. Nunc molestie metus leo, eu sagittis enim dapibus id. Nam eu tincidunt justo, et fermentum mi. Curabitur vitae sem eu massa imperdiet dictum. Quisque tempor mi non arcu convallis, quis accumsan elit commodo. Maecenas dictum urna quis fringilla ultricies. Mauris sed leo vel orci tempor condimentum. Praesent posuere sapien lacinia ligula tempus consequat eget quis erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;\n" +
"\n" +
"Nulla sit amet pharetra turpis. Donec nulla est, suscipit at mauris quis, ultrices consequat justo. Sed bibendum est non pulvinar aliquam. In hac habitasse platea dictumst. Ut semper purus eu arcu sollicitudin, ac vehicula justo rhoncus. Sed fringilla lobortis orci, at sollicitudin lectus fringilla id. Curabitur mauris eros, fringilla sed urna vel, tincidunt dignissim tellus. Nullam aliquet ex non rhoncus eleifend. Aenean sit amet arcu libero. Vestibulum sed luctus velit. Curabitur sed augue laoreet felis volutpat pharetra. Phasellus ac imperdiet eros. Sed gravida ipsum urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin sit amet mollis est, et pulvinar velit. Donec in vulputate nibh.\n" +
"\n" +
"Integer porttitor metus in sem pellentesque feugiat. Duis euismod fermentum nunc, vulputate blandit nibh fermentum ut. Sed euismod urna et aliquam tristique. Nullam gravida nunc eu facilisis ullamcorper. Mauris justo leo, malesuada sed massa vel, rutrum dapibus ipsum. Aliquam leo quam, ultricies in nulla eu, maximus dictum felis. Suspendisse tincidunt euismod ornare. Duis et massa nec justo placerat fringilla. Donec in rhoncus lacus. Pellentesque maximus orci vel nibh suscipit fermentum. Sed tincidunt augue sit amet tempus volutpat. Integer consectetur neque in cursus cursus. Fusce interdum, leo a iaculis posuere, velit velit consectetur massa, nec dapibus orci magna eget orci. Vestibulum ac ante et ex posuere gravida quis vitae urna. Quisque congue condimentum ex.\n" +
"\n" +
"In hac habitasse platea dictumst. Sed lobortis quam ac felis vestibulum, eu convallis lorem imperdiet. Donec malesuada lobortis lectus non tincidunt. Quisque congue eget enim tempus accumsan. In vitae nulla aliquam, finibus leo eu, lacinia nisi. Cras vitae mauris placerat, euismod dui vel, eleifend lacus. Fusce pulvinar malesuada neque at pretium. Vestibulum metus eros, lobortis at facilisis vel, ultricies id est. Duis consequat magna vitae accumsan rhoncus. Sed et massa gravida, rutrum dui eget, venenatis nisl. Aliquam rutrum vel orci at rhoncus.\n" +
"\n" +
"Suspendisse potenti. Vivamus arcu dolor, lobortis sed augue nec, gravida varius nisi. Maecenas a augue ipsum. Aliquam laoreet odio at commodo tempus. Sed ac metus arcu. Quisque congue mollis lorem vel lacinia. Sed aliquet ornare tortor, sed cursus magna ornare at. Nullam facilisis placerat turpis, sit amet convallis nulla interdum at. In commodo finibus luctus. Pellentesque non vestibulum lacus, sed pulvinar turpis. Proin ornare enim sed feugiat accumsan. Cras lacinia nibh eros, ut congue ante tincidunt tristique. Vivamus quis ante et massa feugiat lobortis eu sit amet nisi.\n" +
"\n" +
"Aliquam fermentum a sem sagittis fermentum. Nam et pretium quam. Etiam et sem ac diam lacinia molestie sed at magna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec facilisis imperdiet arcu et elementum. Vivamus consectetur, arcu at rutrum viverra, nunc augue tristique augue, vel malesuada quam lorem ut nulla. Quisque dui erat, faucibus id nibh vel, suscipit dapibus ante.\n" +
"\n" +
"Nunc ac lobortis sem. Morbi feugiat ultricies sem non aliquet. Nullam lacus eros, dapibus sodales dolor malesuada, bibendum rhoncus nisi. Donec dictum, metus et vulputate blandit, arcu leo mattis turpis, eget sagittis risus quam ac est. Nunc id purus id eros rhoncus cursus. Sed volutpat sollicitudin tortor. Proin non mauris arcu. Vestibulum rhoncus lacus nibh, vel finibus tellus posuere ac.\n" +
"\n" +
"In sit amet molestie diam, non semper justo. Duis lacinia sed ligula quis malesuada. Suspendisse potenti. In hendrerit risus vitae ex eleifend eleifend. Nam risus nibh, facilisis vel nibh eget, commodo feugiat arcu. Suspendisse pharetra tortor sit amet sem commodo, nec iaculis ante lacinia. Nullam ornare arcu sit amet mauris venenatis, quis hendrerit leo eleifend. Pellentesque vestibulum dolor sed faucibus placerat. Quisque vulputate porta felis ac aliquet. Pellentesque elementum lobortis orci non consequat.\n" +
"\n" +
"Vivamus sodales felis a ligula dignissim convallis. Nullam ut justo scelerisque, consequat nibh sit amet, dignissim tellus. Etiam vel sem a sem fermentum egestas. Integer et massa molestie, consectetur ipsum ac, lacinia risus. Sed et blandit turpis. Aenean ut purus ac eros posuere gravida vel ut dui. Sed ultricies fermentum efficitur. Curabitur eget lacus posuere, dapibus odio tempus, varius eros. Vivamus consectetur varius sem sit amet faucibus. Phasellus id dapibus nisi. Etiam ornare iaculis diam, eu varius tortor dictum id. Nulla eget massa non sapien gravida ultrices.\n" +
"\n" +
"Aenean et elit sed lorem molestie pharetra. Sed imperdiet faucibus mi, venenatis aliquet metus viverra vel. Donec accumsan sapien in risus ornare, at tincidunt risus malesuada. Phasellus cursus sem et fermentum scelerisque. Etiam nisl sem, consequat nec facilisis eu, rutrum sed lorem. Vestibulum est felis, fermentum eget eros lacinia, luctus ultrices est. Nullam pulvinar pellentesque augue vitae elementum. In fringilla nunc magna, eu viverra sem congue venenatis. Curabitur auctor eros vel dapibus pharetra. Ut in nulla in magna lacinia pharetra a sed ligula.\n" +
"\n" +
"Cras non aliquet dolor. Pellentesque ut ipsum id diam convallis fermentum. Suspendisse semper pretium magna, nec faucibus lorem vehicula in. Curabitur rhoncus enim felis, ac posuere nisl malesuada a. Mauris pharetra tincidunt felis, nec molestie ex suscipit a. Maecenas lacinia lobortis pharetra. Nullam eu felis euismod, feugiat velit ac, tempor massa. Etiam at lacus vel libero elementum ullamcorper. Nulla nec sagittis libero. Nulla in neque egestas, cursus elit ac, sagittis sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam rhoncus augue est, ut rhoncus nulla varius non. Nunc ac augue est. Sed eleifend sollicitudin ullamcorper. Phasellus ultrices commodo elit non fringilla. Nullam vitae pharetra mi.\n" +
"\n" +
"Nunc finibus dapibus venenatis. Duis ac urna orci. Maecenas consectetur orci lacus, sit amet lobortis ex faucibus vel. Suspendisse commodo condimentum massa vel venenatis. Mauris non enim dui. Suspendisse potenti. Suspendisse fermentum facilisis lorem at tempus. Vivamus ultricies tellus sagittis elit aliquam, at tincidunt ipsum imperdiet. Nullam consectetur tristique convallis.\n" +
"\n" +
"Aenean aliquam id est ut posuere. Pellentesque metus lacus, porta a urna a, laoreet eleifend risus. Phasellus posuere ex est, vitae gravida risus hendrerit et. Vivamus ut felis quis lectus imperdiet dictum. Vestibulum varius mollis fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec hendrerit risus. Phasellus porttitor risus ex, eget porta dui consectetur eget. Proin lacus leo, pellentesque at sollicitudin quis, tincidunt non augue. Fusce consectetur mi ut velit lacinia tempus. Suspendisse diam est, ullamcorper eget bibendum id, placerat eget magna. Vivamus auctor convallis risus.\n" +
"\n" +
"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam elit nulla, volutpat ut sodales in, congue nec odio. Maecenas leo felis, cursus nec felis eget, laoreet venenatis turpis. Pellentesque quis dignissim ante. Etiam in eleifend purus. Nulla quis nulla quis leo congue convallis a sed ipsum. Sed eu accumsan felis, non scelerisque lectus. Aenean ullamcorper convallis dolor.\n" +
"\n" +
"Morbi bibendum, eros vel lobortis bibendum, ante augue mollis tellus, vel semper metus neque in elit. Etiam eleifend ex at lectus blandit venenatis. Donec sit amet ipsum nibh. Mauris nunc tortor, interdum sit amet hendrerit a, fringilla vel risus. Etiam elit tortor, dapibus pellentesque pellentesque et, aliquam vel enim. Mauris faucibus nec nulla id semper. Suspendisse dictum sem non quam vestibulum, id aliquam ex ornare. Nunc pulvinar ligula eu sem eleifend gravida. Nulla in sem a risus rhoncus tempus vehicula at purus. Nulla eleifend nisi erat, nec elementum turpis pulvinar sed. Maecenas urna libero, ullamcorper nec dui nec, ornare gravida turpis. Nunc ut leo mauris. Duis sit amet ipsum purus.\n" +
"\n" +
"Curabitur vulputate nibh vel quam varius, in viverra neque efficitur. Praesent gravida congue odio at tincidunt. Nam a faucibus ante, sed consectetur magna. Pellentesque ullamcorper rutrum est quis sodales. Fusce condimentum massa id metus dignissim, nec ultricies nisi rhoncus. Cras ligula elit, laoreet placerat ligula quis, finibus luctus enim. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse lacus ligula, hendrerit et quam et, cursus laoreet quam. Cras quis elementum nulla. Vivamus eleifend eros lectus, vulputate elementum nulla fermentum in. Etiam et ornare sem, bibendum imperdiet ligula. Curabitur eu ante augue. Fusce varius sem a neque maximus, in eleifend eros varius. Curabitur pharetra diam diam, at placerat libero porta vel. Ut facilisis ultricies tempus. Aliquam erat volutpat.\n" +
"\n" +
"In rutrum posuere orci, vitae blandit est vulputate ut. Vestibulum sit amet rhoncus arcu, et accumsan nisl. Integer maximus tempor sollicitudin. Aenean posuere elit sed erat vehicula, quis tincidunt augue semper. Sed et vulputate ligula, sit amet aliquet diam. Mauris id purus nunc. Integer tincidunt nulla non erat congue, sit amet sollicitudin sem vulputate. Curabitur ut quam ut justo molestie varius. Sed aliquam dui sed mauris semper gravida. Donec et consectetur enim.\n" +
"\n" +
"Ut varius, lorem ut egestas dignissim, diam risus varius tellus, vel varius elit neque vel sem. Aenean tempor eleifend libero, id pellentesque magna viverra aliquam. Nulla facilisi. Phasellus auctor imperdiet sapien in facilisis. Nam laoreet tempor molestie. Phasellus vitae maximus odio, ullamcorper rutrum sapien. Vestibulum facilisis, purus at aliquam convallis, nunc est scelerisque eros, at blandit lectus nisi sit amet odio. Pellentesque vel eros non neque lacinia semper.\n" +
"\n" +
"Duis suscipit nisl sit amet purus tempor finibus. Integer molestie orci non imperdiet ornare. Nunc elit felis, imperdiet id eleifend vitae, porttitor eget metus. Aliquam convallis ante tortor. Donec ut risus scelerisque, viverra justo sed, fringilla elit. Nullam dignissim neque dui, et ultrices ligula commodo ut. Curabitur nunc eros, pretium vitae ultricies at, tempus at erat.\n" +
"\n" +
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus eleifend nibh in convallis. Curabitur mattis sapien id volutpat egestas. Quisque at metus condimentum, sagittis sem ac, tincidunt turpis. Aenean sed lectus eu ex sollicitudin bibendum. Sed eget dictum lorem, a feugiat sapien. Nunc id lectus quis tortor accumsan molestie sit amet at nibh. Maecenas malesuada nisi id nisl elementum, quis maximus turpis maximus. Morbi sollicitudin tincidunt dignissim. Nullam nisl risus, convallis vel urna nec, feugiat mattis lorem. Mauris malesuada, est cursus dignissim semper, lacus lorem luctus augue, vel posuere velit diam vitae libero. Nulla facilisi.\n" +
"\n" +
"In feugiat ex quis ante consequat, non vehicula dui pellentesque. Cras eget quam sed magna tempus malesuada. Donec rhoncus sem elit, at blandit mauris consequat quis. Integer egestas lectus non justo egestas rhoncus. Morbi aliquet libero viverra ipsum porta elementum. Ut cursus, magna sed aliquam sagittis, elit neque blandit urna, id ultrices elit sapien in erat. Nulla pretium tempus magna sed varius. Maecenas auctor ligula ac purus consectetur gravida. Cras eros nunc, tincidunt quis massa in, elementum maximus tellus. In pretium est id eros aliquam pharetra. Phasellus vel venenatis lacus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin pretium turpis sed viverra mattis. Sed fermentum dolor sed mollis vestibulum. Suspendisse egestas at felis sed vehicula.\n" +
"\n" +
"Quisque ornare sapien ut blandit pretium. Nam libero sapien, fermentum ac fringilla vitae, pharetra eget urna. In hac habitasse platea dictumst. In vel nulla ex. Cras scelerisque est nec sem cursus porta. Donec posuere feugiat luctus. Vivamus cursus feugiat tortor. Nulla maximus eros id est scelerisque, nec consequat ligula fringilla. Fusce id eros in arcu faucibus convallis a pulvinar tellus. Curabitur porttitor cursus neque at tristique.\n" +
"\n" +
"Suspendisse vestibulum fringilla quam, nec volutpat dui pretium ut. Duis eget massa lectus. Quisque at accumsan turpis, et rutrum magna. Nulla eu feugiat ex, a eleifend odio. Donec dapibus pellentesque felis, suscipit lobortis dui. Vestibulum mauris quam, eleifend ut ligula nec, consequat ornare lacus. Phasellus vitae elit ullamcorper, sagittis est eget, luctus justo. In dui mauris, iaculis vulputate ullamcorper sit amet, placerat non nibh. Phasellus id sapien porttitor, venenatis erat aliquet, euismod magna.\n" +
"\n" +
"Suspendisse lacinia arcu non luctus hendrerit. Vivamus a facilisis est, a lobortis mi. Duis egestas pellentesque augue nec vulputate. Duis at ante tempus, vestibulum tortor non, luctus ligula. Sed sed urna mollis, tempor lectus eget, lacinia ante. Nam vulputate urna hendrerit, luctus lorem id, finibus dolor. Vestibulum scelerisque quis ipsum vitae sagittis.\n" +
"\n" +
"Fusce dapibus malesuada eros non condimentum. Pellentesque sagittis, eros in aliquam lacinia, ligula augue fringilla lacus, vitae iaculis urna ipsum nec velit. Nullam consequat molestie pulvinar. Duis vitae turpis ex. Nam interdum venenatis tortor. Integer sit amet pulvinar magna. Aenean vel blandit neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;\n" +
"\n" +
"Praesent at mauris non velit lobortis lobortis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer in finibus magna. Cras molestie orci id odio pulvinar mollis. Aenean egestas venenatis erat dignissim fermentum. Mauris id metus libero. Proin quam ex, varius in dui et, egestas condimentum massa. Suspendisse potenti. Vivamus vitae dui egestas, porttitor sapien a, vestibulum nisi. Maecenas eros tellus, pulvinar non augue in, pellentesque efficitur erat. Phasellus ullamcorper lorem vitae lacus ultrices eleifend. Morbi porta ex a maximus cursus. Nullam non nulla eu enim elementum dictum.\n" +
"\n" +
"Nulla facilisis, risus id fringilla accumsan, odio urna rhoncus ante, non varius diam risus sit amet lacus. Donec nibh magna, posuere non lacus vitae, vestibulum consectetur nibh. Nam aliquam est in ex auctor malesuada. Ut nec dui placerat, pellentesque nibh sed, venenatis nunc. Proin tristique pretium nisl vitae gravida. Aliquam cursus massa vel ligula scelerisque, efficitur dignissim nisl tincidunt. Vestibulum a sapien quis elit auctor pellentesque. Sed ut lacinia neque, sed commodo nulla. Phasellus faucibus elit sed sem consequat malesuada. Duis hendrerit metus vel nunc vulputate, et hendrerit metus finibus. Vestibulum facilisis mi sed pellentesque luctus.\n" +
"\n" +
"Sed luctus sagittis vestibulum. Sed bibendum a ligula sed dictum. Ut urna augue, varius nec lorem eu, finibus laoreet massa. Cras at enim eget turpis tempus aliquam. Phasellus lectus mi, congue eleifend velit et, aliquam maximus ante. Aenean vel placerat nulla, eu luctus neque. Curabitur placerat, augue eget scelerisque elementum, sem ligula suscipit dolor, vitae pretium tellus metus a sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque mattis elit id elit hendrerit bibendum. Ut sit amet convallis metus, efficitur dignissim velit. Nunc suscipit sapien quis leo iaculis pretium. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam sit amet eros eget urna egestas dapibus.\n" +
"\n" +
"Cras ultricies nec nisi id dignissim. Sed facilisis ultricies ante a posuere. Donec libero nulla, rhoncus eu iaculis elementum, dictum at turpis. Ut ut felis id nibh dictum imperdiet. Etiam vel est quam. Maecenas in molestie leo. Etiam vestibulum diam et quam cursus, pharetra convallis sem accumsan. Nam lobortis aliquam tortor eget aliquam. Aliquam lobortis purus ligula, in auctor enim tempor eget. Curabitur hendrerit condimentum dui non maximus.\n" +
"\n" +
"Vestibulum et lorem urna. Praesent mattis nibh vel elit cursus sagittis. Aliquam sed tellus ornare lectus congue sagittis quis nec nisl. Etiam eget rutrum eros, placerat mollis elit. Nunc ante risus, faucibus eget vestibulum nec, venenatis vel tortor. Morbi ornare tellus a vestibulum mattis. In hac habitasse platea dictumst. Ut nulla nisi, tincidunt a vulputate eu, accumsan nec tortor. Vivamus porttitor elementum consequat. Suspendisse aliquam consectetur justo ut suscipit. Etiam consequat velit non semper mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec non molestie ligula.\n" +
"\n" +
"Sed euismod varius urna, commodo congue tortor condimentum id. Sed ac dapibus elit, sed aliquet turpis. Curabitur ultrices ex aliquet leo tincidunt tincidunt. Donec tincidunt felis elementum, aliquam nisi eu, tristique risus. Phasellus consectetur efficitur tellus, eget porta tellus finibus at. Donec mollis in nunc a egestas. Aliquam pretium enim eros, ut rutrum odio convallis in. In at sem dui. Etiam sit amet nisi malesuada, ultricies mauris sed, suscipit urna. Vestibulum pretium diam et augue pulvinar imperdiet. Integer porta eget lorem nec blandit. Aenean viverra efficitur mollis. Morbi vitae commodo neque, vitae varius mauris. Sed vestibulum nisl at tincidunt imperdiet.\n" +
"\n" +
"Proin non pulvinar justo, non bibendum metus. Suspendisse vel mi leo. Phasellus sit amet lacus dapibus, ultrices dui eu, dapibus ligula. Curabitur sed gravida velit. Nulla a bibendum nulla. Praesent ac mauris ac metus elementum sollicitudin eu sed ipsum. Curabitur nec tempor est, sagittis dignissim nisi. Aenean vulputate suscipit semper. Nullam tincidunt diam purus, sed pretium velit placerat malesuada. Maecenas sed sem lacinia, congue sem ac, mattis eros. Vestibulum vehicula nisl in posuere porttitor. Ut vulputate, sem eu ultrices consectetur, risus diam tincidunt elit, sit amet elementum arcu diam nec ex. Pellentesque luctus metus dictum fringilla bibendum. Curabitur vel augue rutrum lorem euismod egestas vel a velit. Nunc vitae viverra urna, non lobortis enim. Suspendisse est urna, aliquet vitae pharetra volutpat, posuere quis mauris.\n" +
"\n" +
"Quisque non convallis mauris. Nullam tincidunt in sem malesuada pellentesque. Nunc efficitur laoreet consequat. Sed euismod tristique turpis, in fringilla lectus pellentesque id. Curabitur consectetur ligula ac augue lacinia imperdiet. Donec suscipit leo eu quam iaculis, ut egestas mauris lobortis. Donec rhoncus vitae enim eu cursus. In consectetur odio sit amet sodales efficitur. Aenean non ultricies leo. Morbi auctor eu turpis et condimentum. Sed cursus nulla neque, a dignissim risus pretium non. Duis finibus rhoncus lacus a volutpat. Proin nisl est, fermentum at nibh in, imperdiet semper urna. Morbi cursus purus bibendum, porttitor arcu sed, volutpat dolor. Duis congue aliquet augue dictum tristique.\n" +
"\n" +
"Ut imperdiet ante orci, in interdum quam ornare ac. Phasellus pulvinar non metus id sodales. Phasellus eget pretium augue. Etiam quis orci mollis, finibus justo eu, mollis lacus. Duis quis posuere purus. In porta quis erat ac consequat. Nulla ultricies semper maximus. Nullam at efficitur libero, ac condimentum sem.\n" +
"\n" +
"Integer quis velit enim. Phasellus diam augue, elementum eu venenatis sed, vulputate ac lacus. Quisque quis mauris leo. Duis blandit tortor vel orci gravida viverra. Nullam non mauris quis ex fringilla interdum. Cras tortor nunc, molestie ut tortor id, tempor interdum nisi. Pellentesque sollicitudin pulvinar sodales. Praesent luctus commodo maximus. Morbi cursus aliquet elementum.\n" +
"\n" +
"Quisque fermentum interdum tortor. Morbi ut lectus tellus. Vestibulum tempor arcu lectus, at vestibulum eros lobortis et. Vestibulum sed odio felis. Proin efficitur quis mi ac accumsan. Maecenas vel aliquet tellus. Integer neque ipsum, efficitur non eros posuere, consequat pellentesque enim. Praesent tempus augue metus, at malesuada nunc feugiat non. Morbi sit amet elementum neque. In nisi eros, bibendum vitae nisi nec, placerat ultrices est. Cras at elementum orci. Fusce posuere sed odio sed laoreet. Nulla consequat neque a felis aliquam, gravida fermentum eros malesuada. Nullam nec ipsum vel dolor vehicula volutpat. Nulla eu arcu id nisl porttitor interdum eu vitae dui.\n" +
"\n" +
"Vivamus tincidunt metus ex, eget fermentum metus scelerisque a. Vivamus egestas nec orci non lacinia. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in nunc ex. Etiam vestibulum suscipit dui, eget molestie felis fringilla vel. Nullam nec hendrerit urna. Nulla sed dapibus mauris. Aenean commodo felis eget tempor blandit. Quisque vitae sem viverra, ullamcorper elit ac, auctor augue. Proin interdum aliquam elementum.\n" +
"\n" +
"In consequat nibh quis suscipit ultricies. Aliquam rutrum pellentesque pulvinar. Morbi a posuere velit, at pulvinar metus. Maecenas massa augue, pulvinar sit amet rutrum eget, rhoncus sit amet quam. Sed a orci urna. Praesent sodales risus sit amet augue lacinia porta. Vivamus id elit sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec vitae lacus eget elit posuere consectetur ut in nisl. Ut vitae pellentesque eros, et suscipit elit.\n" +
"\n" +
"Proin id venenatis lacus, ut tincidunt leo. Quisque venenatis non justo ac egestas. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut facilisis ornare pharetra. Ut eu mollis velit. Aenean diam justo, fermentum eu velit nec, fermentum sagittis tortor. Mauris vestibulum, ante quis tempor aliquet, purus metus porttitor orci, non pellentesque magna risus sed urna. Nam tincidunt congue imperdiet. Duis elit eros, mattis id varius in, rhoncus quis erat. Nam in nisl nec ex lacinia commodo et eget leo. Curabitur elementum elit sed facilisis hendrerit. Maecenas feugiat ante nec maximus sodales.\n" +
"\n" +
"Morbi ac pellentesque lorem, sit amet tempus elit. Nunc tellus magna, pulvinar tempus lacus quis, tristique ullamcorper urna. Morbi nec ultrices sem. Sed ut blandit nisl. Vivamus et ligula tellus. Fusce vestibulum diam sed egestas auctor. Pellentesque vehicula magna elit, ut sodales risus imperdiet nec. Aliquam dignissim luctus lacus vitae malesuada. Suspendisse blandit at lorem sed dictum. Cras tincidunt convallis magna sed faucibus. Duis purus neque, malesuada et dignissim at, consectetur id tortor.\n" +
"\n" +
"Duis id diam viverra risus lacinia blandit. Donec sed venenatis ligula. Donec at ante porta, rhoncus lorem id, porta sem. Morbi facilisis finibus dui, facilisis ullamcorper nibh luctus ac. Quisque a urna egestas, vehicula dolor quis, imperdiet ligula. Duis a porttitor velit. Sed dignissim, odio non egestas vehicula, lacus turpis blandit eros, quis bibendum ligula augue sed quam. In eget placerat enim, a cursus sapien. Vivamus faucibus cursus purus. Vestibulum tortor massa, imperdiet ut nisi in, hendrerit fermentum nibh.\n" +
"\n" +
"Nulla at neque et orci ornare lobortis ac non tortor. Cras efficitur sed orci ac tempor. Maecenas feugiat sed augue quis blandit. Praesent elementum facilisis ex. Aenean rhoncus ligula tristique erat pretium tempus. Vestibulum rutrum massa eros, quis elementum nisi tempus non. Duis viverra leo a neque fermentum sodales. In hac habitasse platea dictumst. Sed vitae tortor ut dolor rhoncus egestas.\n" +
"\n" +
"Duis et erat vitae dolor auctor mattis. Curabitur eu dapibus arcu. Donec non vulputate massa. Suspendisse purus lorem, ultricies et lorem ut, lobortis hendrerit sapien. Sed scelerisque orci ac convallis volutpat. Curabitur eget quam dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed non lacinia nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce gravida, leo molestie porttitor posuere, quam orci rutrum leo, sit amet vestibulum mauris lacus sed eros. Duis hendrerit mauris at dui porta finibus. Nullam varius purus nec mi euismod, et laoreet lorem euismod. Integer volutpat arcu ac mauris euismod tincidunt. Mauris elementum mi a tortor congue posuere.\n" +
"\n" +
"Donec eu lorem sapien. Quisque sem nibh, efficitur sed nisi eget, convallis blandit augue. Vestibulum in sem semper, consectetur purus sit amet, molestie libero. Mauris a porttitor lorem. Sed et eleifend enim. Nullam varius enim eget porta varius. Duis suscipit quam vel sapien euismod hendrerit. Aliquam finibus posuere metus ut laoreet. Morbi id lorem eget ligula vehicula maximus. Donec quis massa cursus, facilisis mauris tristique, molestie justo. Praesent tincidunt est vel sapien maximus convallis. Nulla lacinia dui non dolor eleifend, vel blandit leo egestas. Ut convallis varius volutpat. Aenean malesuada laoreet erat, porttitor fringilla nunc viverra id. Cras sagittis pretium justo, eget scelerisque est lobortis ut. Praesent mollis ante felis, ut condimentum orci pellentesque nec.\n" +
"\n" +
"Duis blandit magna quis nisi blandit tempus. Etiam interdum nulla non leo luctus, sit amet volutpat diam molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus egestas ante eget ligula eleifend elementum. Curabitur vel tempor erat, a laoreet mi. Mauris eu ante nec dui venenatis lobortis. Praesent laoreet odio lacus, nec blandit neque posuere vitae. Fusce sed tincidunt ipsum. Fusce at diam eu dolor dapibus varius. Etiam venenatis ex sit amet velit viverra sodales. Fusce augue est, aliquam non fringilla ultricies, dapibus ut mi. Quisque cursus ultricies magna in ornare. In non lectus vestibulum, congue diam a, commodo purus. Maecenas porttitor eu lectus viverra suscipit. Nam faucibus dui vel velit finibus dictum.\n" +
"\n" +
"Vestibulum fringilla nisi et sapien placerat rhoncus. Quisque ultrices, metus et aliquam molestie, nisl lectus auctor turpis, at fermentum dui nulla vitae lorem. Nullam felis velit, congue eget metus et, tincidunt pharetra dui. Praesent in dui lacinia arcu sollicitudin pulvinar ut eget augue. Nullam pharetra hendrerit ornare. Quisque tristique orci sit amet nisi viverra, pharetra rutrum ante laoreet. Vestibulum eu orci ac libero auctor volutpat vel et tortor. Nam laoreet justo eget condimentum finibus. Sed vitae mi tincidunt justo sagittis rutrum eu et orci.\n" +
"\n" +
"Nulla facilisi. Nulla dictum, leo et pretium venenatis, lacus mauris elementum erat, ac placerat tellus odio sit amet arcu. Aliquam faucibus eu tortor a hendrerit. Sed efficitur non turpis eu lobortis. Integer vel leo ultricies, lobortis nulla eu, tincidunt ligula. Sed a aliquet mauris, sit amet ornare metus. Etiam a commodo mauris. Aliquam porttitor justo in risus scelerisque convallis. In lobortis fringilla sodales. Ut vitae arcu at justo placerat egestas. Aliquam ut fringilla ex. Donec gravida turpis aliquet pharetra ornare. Mauris et augue eget lorem sollicitudin euismod id sit amet mauris. Maecenas rutrum, massa non auctor gravida, mauris augue gravida nisi, a venenatis massa metus eu massa.\n" +
"\n" +
"Maecenas vel pulvinar orci. Aliquam eget justo vulputate, hendrerit sapien sit amet, gravida lacus. Ut viverra felis vel lobortis consectetur. Donec ex ex, rutrum faucibus tempor vitae, imperdiet nec nibh. Aenean fermentum in ipsum vitae cursus. Praesent a fermentum mauris, suscipit tristique quam. Maecenas sem ligula, sodales in posuere sodales, sodales sit amet ante. Suspendisse eleifend quam in porta laoreet. Nulla facilisi.\n" +
"\n" +
"Nulla quis lorem ornare, eleifend tortor at, dictum ex. In hac habitasse platea dictumst. Pellentesque tempor tincidunt diam, in iaculis nisl suscipit eu. Aenean accumsan arcu ut ornare porta. Phasellus sit amet sem lectus. Aenean venenatis libero eget quam pharetra vestibulum. Etiam aliquet felis a aliquet fermentum. Praesent a mollis sem.\n" +
"\n" +
"Donec lectus nisl, finibus non nibh non, euismod condimentum erat. Sed a turpis ac arcu gravida tincidunt. Suspendisse non lacus a erat faucibus vehicula. In hac habitasse platea dictumst. Curabitur nec arcu nulla. Vestibulum in facilisis quam, id iaculis velit. Nam a lacinia felis. Etiam arcu mi, feugiat a vestibulum at, eleifend ut metus. Donec lacus leo, dictum in orci quis, semper malesuada odio. Sed consectetur leo quis purus maximus, et commodo libero imperdiet. In magna lorem, consectetur eu facilisis non, tincidunt sit amet ante. Nullam sodales dolor eu est condimentum gravida. Etiam ut sapien eu quam efficitur viverra. Mauris sit amet lacus eget enim dignissim rutrum. Pellentesque ac rutrum dolor, ut tincidunt augue. Nullam interdum erat id turpis consequat, in maximus sapien pretium.\n" +
"\n" +
"Nam tellus quam, consectetur vitae lacinia in, consequat eget arcu. Curabitur quis lorem enim. Morbi nibh odio, congue at tempor vel, rutrum id erat. Nam finibus, est ac scelerisque efficitur, velit quam finibus purus, vel rhoncus purus enim a magna. Integer viverra magna quis est venenatis, rutrum ullamcorper lectus sagittis. Morbi accumsan iaculis eros, et varius risus tincidunt vitae. Phasellus ac volutpat mauris, vel rhoncus augue. Nam vestibulum a felis eu porta.\n" +
"\n" +
"In est libero, consectetur in venenatis eget, lobortis a lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus venenatis tellus eu nulla convallis ultricies. Pellentesque vitae elit vel ex sollicitudin rhoncus. Cras condimentum enim vitae magna pharetra, consectetur pretium augue bibendum. Nam in consequat augue. Donec pulvinar mattis cursus. Nulla facilisi. Mauris mollis ipsum magna, mattis dictum mauris efficitur ac. Donec et euismod felis, sed luctus elit. Pellentesque sagittis luctus odio, sit amet lobortis ex sagittis commodo. Ut suscipit lacus quis consequat sagittis.\n" +
"\n" +
"Sed iaculis augue eu congue pharetra. Ut imperdiet orci nec libero sollicitudin, vitae congue orci molestie. Nullam imperdiet velit sit amet massa consequat, ac elementum odio porta. Curabitur non volutpat massa. Nulla facilisi. Curabitur laoreet, purus ac varius egestas, risus felis sollicitudin nibh, ornare luctus orci tortor vel libero. Vestibulum euismod enim a ex hendrerit, in ultricies erat euismod. Proin eget interdum elit. Nulla ultricies nibh risus, sed elementum magna ultrices sit amet. Morbi congue, magna quis ornare tempus, mauris massa convallis sapien, at vehicula dui lorem quis nulla. Nullam ullamcorper turpis ac neque pharetra, ut placerat arcu posuere. Suspendisse sed condimentum tellus. Mauris dignissim pharetra ligula eget ultricies. Duis blandit mollis vehicula. Fusce lacinia est massa, et dignissim mauris lobortis sit amet. Curabitur eros tellus, convallis a magna vel, ornare dictum odio.\n" +
"\n" +
"Cras non ultricies ante. Mauris eu ultricies felis. Aenean lacinia venenatis ex at elementum. Nam laoreet sapien a neque vestibulum, vel laoreet est feugiat. Aenean volutpat nisi nec neque vehicula sagittis. Aliquam ut consequat lorem, in congue sapien. Aliquam varius leo nunc, nec blandit tortor vestibulum at.\n" +
"\n" +
"Donec lobortis vestibulum justo sed feugiat. Phasellus augue dui, maximus eget elit eget, dapibus imperdiet enim. Curabitur quam felis, ultricies eu volutpat ac, posuere at lorem. Nulla urna velit, ornare vitae vehicula et, fringilla sed lectus. Sed a elementum elit, in vulputate lacus. Fusce sollicitudin nisl a facilisis egestas. Phasellus placerat metus mi.\n" +
"\n" +
"Donec urna odio, cursus id bibendum in, aliquet eu magna. Integer maximus augue ac ex maximus, quis laoreet ipsum congue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec tempor, turpis ornare aliquet suscipit, magna risus interdum ipsum, vel ultrices nisi justo a neque. Suspendisse euismod est lorem, quis lobortis odio tempus quis. Nunc porttitor neque ut accumsan rhoncus. Donec consequat feugiat feugiat. Donec sed orci et ipsum ullamcorper tristique. Praesent enim ante, gravida fermentum lorem vitae, pellentesque ultricies mi. Etiam sodales id diam vel accumsan.\n" +
"\n" +
"Fusce mollis purus eu egestas scelerisque. Morbi et eros eros. Sed euismod vel erat ut consectetur. Suspendisse ultricies maximus orci non mattis. Nulla efficitur felis at odio porta, ut convallis ante dictum. Aenean iaculis neque id magna fermentum, at commodo urna efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi quis lectus convallis, mattis ante quis, aliquam magna. Proin faucibus eu tellus vel placerat.\n" +
"\n" +
"Mauris vitae auctor lorem. Sed sit amet diam blandit est finibus egestas et aliquet lorem. Curabitur efficitur bibendum est a auctor. Cras condimentum lacinia libero, ut volutpat erat. Nunc nec lacus vestibulum lectus sagittis tristique. Fusce non purus non diam imperdiet lobortis imperdiet eget ligula. Suspendisse eu vehicula enim. Duis dolor justo, venenatis id tincidunt id, gravida et leo. Fusce convallis finibus faucibus. Aliquam suscipit dui sit amet ligula rutrum egestas. Sed semper, mi et pulvinar gravida, sem velit pharetra orci, eu consequat ipsum nisi et magna. Integer convallis libero odio, vitae sodales arcu dictum id.\n" +
"\n" +
"Donec nulla purus, semper id venenatis quis, sagittis vitae augue. Suspendisse eget ex quis quam pharetra malesuada a vitae odio. Maecenas vitae erat viverra, suscipit neque eu, elementum nisi. Donec consectetur eros a urna vestibulum, vitae ullamcorper elit finibus. Maecenas sit amet nibh mauris. Quisque tincidunt lacus in purus sollicitudin, ut hendrerit neque vulputate. Aliquam enim mauris, tincidunt sit amet luctus at, iaculis eu sem. Nulla quis venenatis lacus, quis tincidunt tellus. Sed porttitor venenatis velit, quis varius mi consectetur a. Phasellus ultrices consequat placerat. Phasellus feugiat velit nec tortor facilisis, eu pellentesque mi viverra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean in eleifend augue. Pellentesque fringilla sollicitudin nisi, at condimentum leo accumsan a. Pellentesque ullamcorper lectus libero, a iaculis enim faucibus nec. Nulla in lacus blandit, dapibus justo sed, maximus nisl.\n" +
"\n" +
"Phasellus dapibus sapien id porttitor porta. Donec cursus scelerisque diam, a molestie neque bibendum id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In in blandit est. Pellentesque bibendum pretium cursus. Mauris laoreet justo nec orci mattis, et tristique enim tristique. Donec diam ipsum, aliquam quis condimentum ut, porttitor eget tellus. Aliquam consectetur neque ac est rutrum varius. Nulla suscipit mollis condimentum. Maecenas vel leo sed velit molestie iaculis. Etiam pretium efficitur aliquet. Suspendisse potenti. Donec sed dolor vitae dolor vehicula consequat et ac mi. Integer iaculis orci ante, et cursus ante maximus ut.\n" +
"\n" +
"Nulla gravida lorem orci, ut feugiat magna dictum eu. In ac ornare justo, non ornare est. Ut eget felis ut ex varius pharetra. Praesent ac lectus ante. Morbi ac dui vel sem pretium vulputate. Mauris vel odio eu ex pulvinar egestas in eget purus. In vitae porta neque, vitae bibendum purus. Suspendisse in sapien in purus porttitor lacinia. Integer justo tortor, vehicula eu dui eget, molestie euismod sapien. Nullam accumsan massa nec viverra vestibulum. Nullam sit amet leo a velit finibus viverra. Aenean in erat sit amet lorem finibus porttitor pellentesque quis augue. Duis mattis accumsan odio, sed gravida ligula porta sed. Ut eleifend laoreet efficitur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam auctor justo in felis eleifend tincidunt.\n" +
"\n" +
"In id faucibus neque. Donec augue risus, ultricies sit amet nisi nec, cursus lacinia elit. Duis quis sagittis est. Pellentesque lobortis in turpis ac ultrices. Pellentesque vehicula commodo facilisis. Fusce id turpis auctor lacus laoreet rutrum ac sed lacus. Donec interdum nec sapien convallis rhoncus. Nunc sit amet mauris auctor, porta purus in, tristique elit. Phasellus consequat est odio, sed cursus nisi faucibus at. Morbi lacinia laoreet luctus. Nunc a mattis felis, ullamcorper lacinia ligula.\n" +
"\n" +
"In sit amet interdum mauris. Proin non nisl non ex dignissim placerat. Curabitur nec neque ullamcorper, venenatis massa eget, condimentum dolor. Aenean lacinia nunc vel augue pretium, eget tristique est mollis. Praesent a tincidunt dolor. Vestibulum id posuere odio. Phasellus ultricies sit amet nibh at commodo.\n" +
"\n" +
"Praesent fringilla sit amet ex eget aliquam. Phasellus at nisl ex. Etiam blandit faucibus suscipit. Donec consectetur vitae metus sed dictum. Ut sed nisi id nisi dignissim consequat. Aenean id dignissim purus. Aliquam commodo, sapien in accumsan venenatis, turpis lorem pulvinar nulla, eget sagittis turpis diam eu arcu. Integer sit amet elit et magna lacinia sagittis a ac ipsum. Donec commodo massa sed odio euismod fringilla. Morbi feugiat interdum mi eu molestie. Vivamus interdum, libero eget sagittis vestibulum, lacus lacus feugiat orci, finibus tristique purus diam eget ipsum. Integer condimentum diam ac lorem ultrices, id interdum ipsum vulputate. In quis porta nulla. Nulla finibus, ligula in dapibus cursus, sem magna dignissim sem, a venenatis sapien magna vel tortor.\n" +
"\n" +
"Phasellus faucibus vehicula dui, vitae aliquet dui convallis id. Proin nec erat id mi molestie cursus eget id arcu. Aliquam interdum sollicitudin mi eu congue. Curabitur in odio convallis dui egestas fermentum. Integer et venenatis nulla. In auctor ultrices metus non condimentum. Proin ac purus at neque efficitur vehicula. Pellentesque ut gravida arcu. Donec rutrum consectetur rhoncus. Aenean non luctus elit. Pellentesque nec augue erat. Vivamus elementum massa id tristique sollicitudin. Morbi at risus nec risus lobortis consequat quis in est.\n" +
"\n" +
"Ut et nibh eget urna elementum feugiat. Nunc pellentesque orci mi, vel ultricies erat tristique a. Phasellus sed lacus aliquam, placerat mauris quis, accumsan velit. Vestibulum varius nec mi ut aliquet. Nullam a eros est. Nam sit amet velit velit. Sed varius augue quis finibus tincidunt. Maecenas faucibus sem vitae diam suscipit, vitae suscipit orci varius. Donec facilisis, nulla interdum sollicitudin sodales, nulla tortor iaculis felis, ac mattis libero magna sed neque. Vivamus fringilla congue varius. Suspendisse maximus convallis urna, ac placerat tortor pharetra vel. Vivamus et rhoncus nisl. Aenean commodo convallis eleifend. Suspendisse feugiat est tristique, faucibus nulla vitae, sollicitudin est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut tincidunt orci venenatis massa feugiat dapibus.\n" +
"\n" +
"Donec maximus diam vitae ultricies varius. Mauris vulputate nisl felis, a tincidunt sem cursus et. Donec risus orci, accumsan non arcu ac, laoreet pretium tortor. Suspendisse in elementum ex. Quisque ac malesuada sem. Morbi at sapien porttitor, facilisis erat a, finibus ante. In in interdum enim, sit amet elementum turpis. Cras quis venenatis orci.\n" +
"\n" +
"Maecenas lectus felis, fermentum quis finibus nec, suscipit quis justo. Ut nec metus velit. Morbi rutrum metus vel porttitor vulputate. Aliquam eget laoreet nunc. Cras a varius dui, et porta justo. Vivamus convallis quam nec rutrum imperdiet. Pellentesque vitae quam sapien. Quisque a nulla sollicitudin, molestie purus sed, consequat elit. Aenean vulputate finibus consequat. Suspendisse dapibus ultricies metus sed blandit.\n" +
"\n" +
"Vivamus auctor felis nisi, non tempus erat rhoncus ut. Pellentesque venenatis velit lacus, eget iaculis ligula maximus varius. Vestibulum eleifend lacinia scelerisque. Vestibulum a consequat velit, et iaculis eros. Morbi pulvinar vulputate purus non blandit. Proin tempor tortor sed elit luctus cursus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi tempus elit vel consequat vestibulum. Mauris auctor odio at purus viverra, quis convallis dui laoreet. Cras sed metus nec elit lacinia ultrices ut sit amet tortor.\n" +
"\n" +
"Ut sit amet turpis eu enim bibendum tincidunt a sit amet augue. Donec lacinia venenatis metus, semper efficitur enim. Duis bibendum augue a nibh tempus semper. Maecenas elit felis, dictum a pretium sed, rhoncus non leo. Sed lectus urna, vestibulum a eros pretium, tempus imperdiet dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum sagittis condimentum urna, ut egestas sapien egestas non. In nibh sapien, ullamcorper vitae iaculis quis, consectetur at dolor. Aliquam erat volutpat.\n" +
"\n" +
"Sed sagittis velit risus. Etiam ut purus commodo, convallis augue et, malesuada augue. Sed justo quam, scelerisque sed urna ac, tincidunt accumsan massa. Fusce at dapibus nulla, vel porttitor nunc. Phasellus id elit at turpis pretium maximus at non est. Vivamus sed turpis nunc. Quisque fermentum magna eget risus lacinia, eu pretium nisi porta. Duis finibus tortor ut elementum interdum. Morbi vulputate odio ac libero consectetur sagittis. Nulla facilisi. Nam tristique dapibus neque ac cursus. Nulla lobortis dictum leo ac molestie.\n" +
"\n" +
"Nunc quis viverra lorem. Sed eget libero at lacus porttitor blandit vel a tellus. Cras vestibulum egestas turpis, a condimentum odio venenatis in. Sed tellus massa, varius et arcu ut, fermentum semper metus. Nulla nisi magna, laoreet nec velit non, suscipit accumsan elit. Morbi elementum nibh lorem, eget viverra justo venenatis non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum congue orci vitae lacinia eleifend. Fusce dictum consequat lectus eget scelerisque. Quisque molestie mauris non ultrices vehicula. In est felis, porta vitae nibh a, scelerisque rhoncus lorem. Cras malesuada varius fringilla. Nullam eu velit sed nisi aliquet dictum. Maecenas a dui odio. Nullam nunc ligula, tincidunt ut mattis vel, rutrum eu odio. Phasellus facilisis mauris tortor, sit amet tincidunt lectus venenatis id.\n" +
"\n" +
"In egestas ut dolor ac bibendum. Ut ut sapien a nisl rhoncus feugiat in et dui. Aliquam in metus nunc. Nulla porta arcu a magna iaculis convallis. Sed imperdiet, nisl ut volutpat tempus, felis odio blandit neque, id scelerisque lorem nisl eu lorem. Fusce bibendum aliquam diam, nec tempor risus facilisis vel. Morbi fermentum, leo in iaculis condimentum, nulla massa imperdiet lorem, ac consectetur ipsum metus eget tellus. Suspendisse sit amet accumsan sem. Suspendisse dapibus tincidunt augue, in interdum augue aliquam et. Vestibulum vitae egestas lorem.\n" +
"\n" +
"Quisque feugiat consequat posuere. Integer placerat semper malesuada. Proin porta quis ex vel mollis. Nulla dictum tempus est at tempus. Sed vehicula purus ullamcorper dolor lobortis vehicula. Aliquam erat volutpat. Cras ullamcorper lectus vitae magna dignissim rutrum. Phasellus posuere sagittis metus, quis ultricies ante fringilla non. Praesent non porttitor mauris. Fusce vel ultricies urna, dapibus eleifend mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla at rutrum est, at laoreet orci. Sed finibus nunc sit amet libero ultricies, ut ullamcorper mauris posuere.\n" +
"\n" +
"Etiam ac ipsum leo. Sed ut auctor metus. Donec maximus, augue et egestas egestas, quam nisl malesuada sapien, eu fringilla erat enim non tortor. Quisque nec lacinia justo. Curabitur eu felis scelerisque, dictum lectus in, placerat leo. Ut at finibus orci, non placerat dolor. Ut efficitur lorem lectus, sed gravida lorem tempus blandit.\n" +
"\n" +
"Fusce bibendum vulputate dictum. Sed bibendum augue vel vestibulum convallis. Cras vehicula hendrerit nisl, sed maximus erat scelerisque porta. Nulla consequat mi dui, sed convallis ex vestibulum ac. Donec purus dui, malesuada nec enim vel, ultricies congue mauris. Vestibulum in nisl non purus feugiat mattis non in lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam eu sem tincidunt, tempor mi nec, ornare nisl.\n" +
"\n" +
"Praesent vestibulum lectus quis ipsum lacinia aliquet. Nunc et pretium odio, eget congue nibh. Suspendisse ornare convallis enim sed porta. Nam pulvinar rhoncus malesuada. Phasellus lobortis ullamcorper orci. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis commodo metus risus, ac aliquam augue feugiat vitae. Vivamus hendrerit posuere est, vitae interdum quam finibus mattis. Pellentesque vel ipsum dapibus, dignissim odio at, vehicula mauris. Suspendisse in ligula in tortor maximus volutpat. Ut eget diam sagittis, porttitor massa vitae, pulvinar est. Sed vel metus a odio facilisis interdum. Mauris ut dignissim metus, sed condimentum felis.\n" +
"\n" +
"Nullam ac felis in massa facilisis porta. Praesent at aliquam nibh, nec varius metus. Quisque maximus neque ut ante molestie, vel interdum sem convallis. Sed sollicitudin diam rutrum pellentesque mollis. Nulla pulvinar non enim ac pellentesque. Duis sollicitudin libero scelerisque lacus fringilla varius. Phasellus sollicitudin, orci id semper sagittis, magna mauris pharetra libero, eu porta velit justo sed mi. Donec molestie metus at turpis fermentum elementum. Aliquam ultricies dignissim ante, et interdum nulla tempor ut. Fusce congue leo quis tellus varius vulputate. Morbi nec libero sem. Aliquam hendrerit non libero in fringilla.\n" +
"\n" +
"Nam vitae sagittis mi, eu rhoncus neque. Duis lacinia arcu ultricies dolor dictum, sed pretium ipsum sodales. Mauris ut sem posuere, luctus erat ut, tempor eros. Aliquam porta augue non justo luctus, vitae suscipit felis consectetur. Vestibulum feugiat sollicitudin aliquet. Donec eget purus eu urna ornare viverra sit amet vitae velit. Praesent euismod ante eget lorem commodo consequat. Ut id enim in velit viverra hendrerit. Nulla sit amet faucibus tellus, vel pellentesque odio. Aenean scelerisque ac mauris in dapibus. Donec sit amet augue vel velit ornare rhoncus sit amet id eros. Vestibulum volutpat dignissim consequat. Donec ligula felis, bibendum convallis hendrerit semper, semper at dolor. Aliquam dignissim luctus feugiat.\n" +
"\n" +
"Suspendisse at enim sapien. Donec consequat tortor eu turpis fringilla luctus. Nulla gravida eu orci nec accumsan. Etiam tellus nisi, imperdiet ac sem ac, feugiat condimentum quam. Nam rhoncus nisl ut nunc pellentesque rutrum. Vestibulum felis leo, dapibus in nibh vitae, vestibulum pellentesque turpis. Duis nulla nibh, tincidunt et fermentum eu, volutpat in velit. Sed convallis justo ac orci euismod convallis. Suspendisse consectetur ultrices ultrices. Vestibulum vulputate libero eu magna varius, lobortis maximus massa gravida. Praesent vitae convallis risus. Quisque quis ornare eros. In cursus pretium rhoncus. Cras at ex felis.\n" +
"\n" +
"Ut tincidunt quis enim eu commodo. Mauris molestie diam sollicitudin, ornare eros vel, sodales velit. Fusce vitae ipsum id diam facilisis lobortis. Nunc pretium erat lorem, in aliquet erat accumsan non. Morbi venenatis eros et eros posuere tincidunt. Cras suscipit, risus id pretium tristique, ex tortor luctus diam, quis dignissim urna mauris vel mi. Morbi porta fringilla nulla, at rhoncus erat lacinia ut.\n" +
"\n" +
"Pellentesque sollicitudin leo at neque ultrices facilisis. Curabitur sollicitudin sed metus eu lacinia. Vivamus et risus ultricies, blandit lorem non, mollis arcu. Ut posuere eros id tortor placerat, ut rhoncus tellus feugiat. Cras rhoncus felis id ligula consequat pretium. Praesent a justo et nulla mattis dignissim ut sit amet magna. Aliquam metus lorem, euismod sit amet lectus ultrices, ultricies malesuada ante. Suspendisse tincidunt enim eu ante venenatis molestie. Sed blandit venenatis massa, nec sollicitudin nisi dapibus a. Duis ac semper massa. Proin turpis ex, gravida eget posuere ut, volutpat ut lectus.\n" +
"\n" +
"Ut ac vulputate nunc, sed consectetur risus. Aliquam tristique, elit sed faucibus fringilla, risus sem placerat erat, quis tincidunt mauris nisl sit amet massa. Pellentesque tristique at sem quis semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis eu aliquet eros. Mauris nec nisi et ex iaculis dictum. Suspendisse ut nulla eu tellus varius hendrerit. Proin euismod dui tellus, eget iaculis mauris dapibus id. Cras ut sem posuere, molestie lacus a, mattis leo.\n" +
"\n" +
"Vivamus ut semper leo, a dictum dui. Ut non augue sit amet ligula luctus convallis. Vestibulum iaculis mattis quam, sit amet blandit tortor luctus sed. Sed pharetra fermentum interdum. Nulla sed velit mauris. Ut maximus laoreet nunc, ac hendrerit lorem varius iaculis. Mauris sollicitudin dolor ac urna ornare vulputate. Morbi pretium dolor neque. Praesent porta id mauris sit amet mattis. Cras consequat risus nulla, id iaculis ex suscipit vel. Nullam lobortis magna sed ante porttitor, at porta sapien aliquam.\n" +
"\n" +
"Fusce dictum posuere quam. Mauris ultrices congue velit, ac consectetur nunc commodo eget. Cras sit amet scelerisque tellus. Proin sed tincidunt arcu, sed iaculis eros. Pellentesque auctor malesuada tristique. Aliquam pellentesque leo a augue dapibus malesuada vel non orci. Curabitur nec dictum erat. Curabitur vestibulum fermentum leo. In sodales nibh neque, at luctus nisi mollis ac.\n" +
"\n" +
"Etiam ultricies, sem nec semper sollicitudin, lorem nibh consequat dolor, mattis tempus velit tortor commodo arcu. Aenean a nisl viverra, euismod sapien at, fermentum nisi. Nunc augue arcu, tristique quis nisi vel, maximus ultrices lectus. Maecenas rhoncus odio lacus, quis bibendum metus scelerisque sed. Sed nec vulputate nulla. Donec et lectus mattis, mollis nisi nec, pulvinar metus. Etiam ullamcorper dolor et pretium tincidunt. Donec condimentum fringilla orci ut tristique.\n" +
"\n" +
"Vestibulum non risus eu turpis vehicula eleifend. Praesent pellentesque id nulla eget elementum. Nulla est massa, venenatis vitae ligula nec, vulputate hendrerit felis. Cras sed tristique sapien. Quisque metus enim, pretium at lacinia sit amet, condimentum sed sapien. Aliquam eget rhoncus purus. Donec id felis non elit lacinia blandit nec ac sapien. Vestibulum lacinia ipsum ac est pharetra, ultricies aliquam mi imperdiet. Duis a laoreet neque. Duis sit amet enim vitae sapien bibendum fringilla at ut nisi. Sed id lectus eu ipsum congue congue ac in sapien. Mauris vulputate lacus ut mauris mattis sollicitudin. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\n" +
"\n" +
"Vivamus vel tortor pellentesque, dapibus lacus vitae, hendrerit est. In in lorem at tellus scelerisque fermentum. Vestibulum ac augue bibendum, scelerisque quam maximus, finibus risus. Vestibulum fermentum venenatis nibh vestibulum porta. Praesent a vestibulum turpis, eget scelerisque urna. Morbi sollicitudin, dui a luctus elementum, felis massa viverra quam, sed dapibus enim turpis id libero. Maecenas non mi eros. Aenean bibendum nibh eu nisi posuere, eget convallis libero sagittis. Duis ullamcorper turpis id hendrerit lobortis. Vestibulum iaculis vitae magna tincidunt consectetur.\n" +
"\n" +
"Mauris convallis semper dapibus. Vestibulum eros lectus, pulvinar a placerat pretium, ullamcorper non turpis. Donec vel nunc imperdiet, condimentum sem in, maximus odio. Nulla vitae luctus massa. Vivamus ut odio velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus risus, lacinia eget justo vel, finibus malesuada nunc. Pellentesque vitae maximus nisl.\n" +
"\n" +
"Mauris eu ligula commodo, euismod ex quis, interdum tellus. Etiam ullamcorper vitae sapien ac gravida. Donec malesuada eu lorem sed porttitor. Integer ut neque non mauris tristique pretium. Mauris dignissim elit eu dolor vestibulum lacinia. Nam viverra bibendum massa, ac fringilla mauris luctus sed. Sed ut urna neque. Ut vel pellentesque massa, nec feugiat tellus. Suspendisse lacinia gravida nisi, vel dignissim turpis cursus non. Nullam blandit lobortis ex. Fusce eget pretium nulla.\n" +
"\n" +
"Vestibulum ut orci viverra, volutpat elit gravida, pellentesque risus. Proin efficitur ante vel felis elementum convallis eget sit amet ante. Fusce ullamcorper turpis lorem, ac condimentum leo placerat et. Phasellus quis arcu non tortor pretium condimentum sed eget sapien. Duis feugiat semper tellus vel euismod. Aliquam nec feugiat sem. Aenean sagittis leo at erat sagittis, ac cursus arcu efficitur. Quisque nunc arcu, vestibulum ut urna in, vestibulum interdum ligula. Sed at nisi facilisis, accumsan nulla a, sollicitudin eros. Donec pulvinar arcu et blandit ultricies.\n" +
"\n" +
"Nulla cursus non risus non luctus. Aenean vitae neque arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ac rhoncus mi, in finibus felis. Ut malesuada facilisis lorem, id scelerisque diam ultricies id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet diam neque. Nam nisi erat, gravida id sem ut, fermentum tempus nisi. Sed aliquet aliquam elementum. Etiam nec nulla dignissim, volutpat risus et, lacinia lacus.\n" +
"\n" +
"Cras vel blandit nulla, et convallis velit. Suspendisse urna metus, sodales vehicula diam aliquet, tristique sollicitudin est. Sed eu congue risus. Sed maximus turpis id diam finibus euismod. Vestibulum commodo massa a nisi dapibus, eget feugiat neque interdum. Sed euismod dui eget lorem ornare, a sagittis nisi efficitur. Aenean erat odio, suscipit at varius sit amet, pulvinar ut sem. Aliquam erat volutpat. Sed ultricies quam sed massa porttitor, congue sollicitudin ante mattis. Etiam condimentum neque sit amet lacus fringilla ullamcorper. Cras volutpat id diam et commodo.\n" +
"\n" +
"Nunc dignissim sem risus, sed aliquam ligula consectetur eget. Duis a diam augue. Ut urna nisi, viverra in pretium ac, varius in nisl. Fusce rhoncus sit amet sapien eget maximus. Donec risus lorem, elementum sit amet lobortis ac, vehicula id est. Praesent non purus ac felis dapibus ullamcorper ut vestibulum sapien. Etiam arcu magna, condimentum a felis non, accumsan vehicula risus. Proin a enim ligula. Aliquam pulvinar tortor ut magna dictum, sed bibendum justo consectetur. Nunc libero sapien, sollicitudin bibendum feugiat non, luctus a augue. Mauris tincidunt, nibh viverra tempor aliquet, odio magna bibendum sem, id convallis mi ligula vel dolor. Etiam dapibus auctor facilisis. Nulla facilisi. Curabitur id condimentum diam, in porttitor est. Mauris auctor, mi in posuere venenatis, risus sem tincidunt nunc, ac faucibus lorem neque id metus. Donec non felis tellus.\n" +
"\n" +
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum lacus lectus, at tristique velit viverra vitae. Nunc vitae est dictum, accumsan metus eu, gravida erat. Nulla at imperdiet justo, in bibendum risus. Donec faucibus, turpis at aliquam volutpat, ex tellus sagittis dui, id aliquam mi velit posuere libero. Mauris eros ligula, molestie sit amet aliquet a, ultricies non eros. Aliquam dictum placerat nunc at aliquet. Nam vel nunc eu quam aliquam commodo et eget felis. Phasellus hendrerit dapibus orci sed pulvinar. Curabitur quis enim purus. Aliquam consectetur eu ex in suscipit. Aenean iaculis massa ex, sed molestie nisi placerat in. Vestibulum consectetur ac erat a varius.\n" +
"\n" +
"Praesent vitae mauris auctor, tincidunt dolor nec, gravida justo. Etiam sit amet nisi ligula. Duis et suscipit tortor. Suspendisse sit amet dui eget odio feugiat accumsan a ut enim. Nunc vitae hendrerit enim, gravida fringilla felis. In tincidunt fringilla nisi, non varius orci venenatis eget. Sed dolor neque, lobortis facilisis semper in, tempor eget nibh. Nam placerat massa quis quam placerat, quis fringilla mi tempor. Cras tempus eros nec urna rhoncus vestibulum. Nullam eget eros elit. Nullam egestas ante eget urna facilisis placerat.\n" +
"\n" +
"Aliquam sodales magna sed ante pellentesque, eget bibendum erat accumsan. Nulla consequat tempus purus, vitae varius sapien dignissim at. Nunc fermentum, diam et euismod dictum, mi metus interdum nisi, quis finibus ipsum dui ut est. Vivamus venenatis gravida ligula. Curabitur ante diam, viverra et turpis in, varius feugiat sapien. Pellentesque varius dignissim nunc et posuere. Aenean faucibus vehicula ipsum ut tristique. Sed quis sapien cursus, feugiat quam vitae, iaculis odio. Aliquam vel risus quis orci euismod vestibulum vel sed mi. Quisque facilisis auctor rutrum. Nulla pretium elit sed nisi ultrices, vel ultricies urna posuere. Sed condimentum et lectus vel viverra. Suspendisse nisi ligula, mollis at lectus dictum, lacinia tincidunt risus. Nullam eget iaculis diam, sit amet sagittis nisl.\n" +
"\n";
        List<HuffKnoop> HuffArray = new ArrayList<>();
        char[] karakters = str.toLowerCase().toCharArray(); //args.toString().toCharArray();
 
        HashMap<Character, Integer> freq = new HashMap<>();
        freq = ferquentie(karakters);
        
        for (char a : freq.keySet())
        {
            //HuffKnoop huff = new HuffKnoop(a,freq.get(a));
            //HuffArray.add(huff);
        }
        
        
    }
    
    public static HashMap ferquentie (char[] chars)
    {
        HashMap<Character, Integer> hash = new HashMap<>();
        for (char ch : chars)
        {
            if (hash.containsKey(ch))
            {
                int waarde = hash.get(ch) + 1;
                hash.put(ch, waarde);
            }
            else
            {
                hash.put(ch, 1);
            }
        }
        return hash;
    }
    
    public static List sorteren(HashMap hash)
    {
        PriorityQueue<HuffKnoop> pq = new PriorityQueue<>();       
        
        return null;
    }
}
